name: Neural_Networks_and_Deep_Learning
channels:
- defaults
dependencies:         # everything under this, installed by conda
- numpy==1.16.5
- scipy==1.3.0
- scikit-learn==0.21.2
- pandas==0.23.4
- matplotlib==3.0.2
- statsmodels==0.9.0
- tensorflow==1.10.0
- keras==2.2.4
- gensim==3.7.3
- jupyter==1.0.0
- beautifulsoup4
- requests==2.21.0
- lxml
- nltk==3.4
- pydotplus==2.0.2
- graphviz
- seaborn==0.10.0
- scikit-image
- plotly==3.10.0
